# Custom Language File for Launcher Customizer

[ejs.app]
title = "Yteria - Lanceur"

[ejs.landing]
mediaGitHubURL = "https://github.com/batminecraft/YteriaLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/EkXCwhWsqx"

[ejs.settings]
sourceGithubLink = "https://github.com/batminecraft/YteriaLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Yteria"
welcomeDescription = "Description ?"
welcomeDescCTA = "?"
